setup: setup contabo VM for docker
Signed-off-by: Kathurima Kimathi <kathurimakimathi415@gmail.com>

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -1,58 +1,43 @@
-# name: Staging Deployment
+name: Demo VM Setup
 
-# on: 
-#   push:
-#     branches:
-#       - feature
+on: 
+  push:
+    branches:
+      - contabo-vm-setup
     
-# jobs:
-#   deploy_to_staging:
-#     strategy:
-#       matrix:
-#         go-version: [1.19.x]
-#     name: Deploy staging server to Google Cloud Run
-#     runs-on: ubuntu-latest
-#     environment:
-#       name: staging
+jobs:
+  setup_demo_vm:
+    strategy:
+      matrix:
+        go-version: [1.23.x]
+    name: Deploy to demo
+    runs-on: ubuntu-latest
 
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v3
+    steps:
+      - name: Setup Contabo VM
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          password: ${{ secrets.PASSWORD }}
+          port: ${{ secrets.PORT }}
+          script: |
+            whoami
 
-#       - id: 'auth'
-#         uses: 'google-github-actions/auth@v0'
-#         with:
-#           credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
-#           project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
+            sudo dnf update -y
 
-#       # Configure Docker to use the gcloud command-line tool as a credential
-#       # helper for authentication
-#       - run: |-
-#          gcloud --quiet auth configure-docker
-     
-#       - name: Build Docker Image
-#         run: |-
-#          docker build -t eu.gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA . 
+            # Install Docker if it's not already installed
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              sudo dnf install -y yum-utils
+              sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
+              sudo dnf install -y docker-ce docker-ce-cli containerd.io
+            else
+              echo "Docker is already installed."
+            fi
 
-#       - name: Push Docker Image to GCR
-#         run: |-
-#          docker push eu.gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GCR_NAME }}:$GITHUB_SHA
+            sudo systemctl enable docker
+            sudo systemctl start docker
 
-#       - name: Deploy to Google Cloud Run
-#         uses: 'google-github-actions/deploy-cloudrun@v0'
-#         with:
-#           service: ${{ secrets.SERVICE_NAME }}
-#           region: 'europe-west2'
-#           image: 'eu.gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ secrets.GCR_NAME }}:${{  github.sha }}'
-#           env_vars: |
-#             ROOT_COLLECTION_SUFFIX=${{ secrets.ROOT_COLLECTION_SUFFIX }}
-#             DEBUG=${{ secrets.DEBUG }}
-#             REPOSITORY=${{ secrets.REPOSITORY }}
-#             AIT_API_KEY=${{ secrets.AIT_API_KEY }}
-#             AIT_USERNAME=${{ secrets.AIT_USERNAME }}
-#             AIT_SENDER_ID=${{ secrets.AIT_SENDER_ID }}
-#             AIT_ENVIRONMENT=${{ secrets.AIT_ENVIRONMENT }}
-#             GOOGLE_PROJECT_NUMBER=${{ secrets.GOOGLE_PROJECT_NUMBER }}
-#             GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
-#             FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }}
-#             ORYX_PROVIDER_CHANNEL=${{ secrets.ORYX_PROVIDER_CHANNEL }}
+            docker --version
